# Generated by Django 5.1 on 2024-08-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam_reports',
            field=models.IntegerField(default=0),
        ),
    ]
